[package]
name = "blenvy_components_example"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { version = "0.15", features = ["dynamic_linking"] }
blenvy = { path = "../../crates/blenvy" }
