[package]
name = "blenvy_relations_example"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { version = "0.14", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.25.2"
blenvy = { path = "../../crates/blenvy" }
